name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - uses: actions/upload-artifact@v2
      with:
        name: upload-apk
        path: |
            ${{github.workspace}}/app/build/outputs/apk/release/*.apk
    - name: Releasing using Hub
      uses: yurakurets/action-release-debugapk@master
      env:
       REPO_BRANCH: master
       GITHUB_TOKEN: ${{ TOKEN }}
       APK_FOLDER: android/app/build/outputs/apk/release/app-release.apk
       APP_FOLDER: android/app
       RELEASE_TITLE: New Build
